# Generated by Django 4.1 on 2023-06-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doc',
        ),
        migrations.DeleteModel(
            name='medicine',
        ),
    ]
